### ISSUE TITLE
[tracking] CDK Workshop V2

### ISSUE THREAD

**Issue by indrora** [aws-samples/aws-cdk-intro-workshop#1170]
Since there's been a lot of conversation about improvements to the CDK Workshop, let's talk about those so they dont' get lost to the sands of time. 

The current outstanding updates to the *current* version of the CDK workshop include:

- [ ] A Spanish translation (tracked in #1125 / #1101 )
- [ ] Various fixes to the content:
  - [ ] #1132 
  - [ ] #931 
  - [ ] #1140 
  - [ ] #1147 
  - [ ] #1169
  - [x] #676 
  - [x] #693 
  - [x] #742 
  - [x] #804 
  - [x] #1139
  - [x] #1049 
  - [x] #1131 
  - [x] #1139   
- [ ]  Requests for improvement to the content overall:
  - [x] #31 
  - [x] #558 
  - [x] #367 
  - [x] #409 
  - [x] #648 
  - [ ] #1048 #1050 
  - [x] #1051 

# What the future of the CDK workshop looks like

I have half a mind to patch up the current content until it's "More or less correct" and make it considered the "Legacy" CDK Workshop. Take a majority of the current content, massage it down, and build it into the "Modern" CDK workshop.

This "Modern" CDK workshop would be divided into:

* Introductory content: Deploying a very simple bucket that you can then call PutObject and ListObjects on, with associated roles and such.
* Intermediate: Deploying a very simple container application that uses DynamoDB and some edge functions to have a page counter, built as a construct.
* Advanced: Deploying a CI/CD pipeline, running the CDK Construct Hub 
* The Toolbox: Things that are useful to know, but don't have a "level" to them:
  - Aspects, Attributes, etc. 
  - Mucking about with CloudFormation

# What I want to know from the community

Given our current CDK workshop, where do you draw the lines between "intro/intermediate/advanced" topics? how would you re-design the CDK workshop today if you could?

**Comment by SamWSoftware** [comment]
I would add a few things for the TypeScript tutorial
- [ ] Use the SDK V3 
- [ ] Use the NodejsFunction construct 
- [ ] Use node 20 and ideally explain what to do if a future node version comes out

I've just created a PR into the v1 cdk workshop with these changes
